Repository El-Primos/blg317, pull requests merged in 2024-12, with the labels that each got.

#28 Info Page for Teams
  .vscode/tasks.json
  backend/app/api/routes.py
  backend/app/utils/data_fetch.py
  frontend/src/app/globals.css
  frontend/src/app/teams/[id]/page.js
  frontend/src/app/teams/[id]/styles.css
  frontend/src/app/teams/page.js
Labels: enhancement, help wanted

#29 Added "Last 5 Games" Table to "Team Info" Page
  backend/app/api/routes.py
  backend/app/utils/data_fetch.py
  frontend/src/app/countries/[id]/page.js
  frontend/src/app/teams/[id]/page.js
  frontend/src/app/teams/[id]/styles.css
Labels: enhancement

#30 Made PlayerInfo Pages
  backend/app/api/routes.py
  backend/app/utils/data_fetch.py
  frontend/src/app/countries/page.js
  frontend/src/app/players/[id]/page.js
  frontend/src/app/players/[id]/styles.css
  frontend/src/app/players/page.js
  frontend/src/app/teams/[id]/page.js
  frontend/src/app/teams/page.js
  frontend/src/app/teams/styles.css
Labels: enhancement

#66 Pagination position error has solved
  frontend/src/components/GridView.js
  frontend/src/styles/styles.scss
Labels: bug

#68 Special delete for Cities Quotes States tables
  database/table_creation/table_cities.sql
  database/table_creation/table_quotes.sql
  database/table_creation/table_states.sql
Labels: enhancement

#83 Updated the countries api
  backend/app/utils/data_fetch.py
Labels: enhancement

#86 79 entering an information page that does not exist shows a page full of nulls
  backend/app/api/routes.py
  backend/app/utils/data_fetch.py
  frontend/src/app/404/page.js
  frontend/src/app/countries/[id]/page.js
  frontend/src/app/games/[id]/page.js
  frontend/src/app/players/[id]/page.js
  frontend/src/app/teams/[id]/page.js
Labels: bug, help wanted
